# Generated by Django 6.0.3 on 2026-03-25 02:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Module display name', max_length=100, unique=True)),
                ('code', models.CharField(help_text="Unique code (e.g., 'EORDER', 'FINANCE', 'HR')", max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, default='package', help_text='Lucide icon name', max_length=50)),
                ('color', models.CharField(blank=True, default='#3B82F6', help_text='Display color hex', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'aw_module',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name of the role', max_length=100, unique=True)),
                ('code', models.CharField(help_text="Unique code identifier (e.g., 'MGR', 'DIR')", max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description of this role')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'aw_role',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('is_approver', models.BooleanField(default=False, help_text='Whether this user can approve requests')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(blank=True, help_text='Assigned role for approval routing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.role')),
            ],
            options={
                'db_table': 'aw_user',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(help_text='External reference ID from the source module', max_length=100)),
                ('title', models.CharField(help_text='Brief title for the approval request', max_length=300)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description')),
                ('payload', models.JSONField(default=dict, help_text='JSON payload from the source module containing all relevant data')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISED', 'Revised')], db_index=True, default='DRAFT', max_length=20)),
                ('current_step', models.PositiveIntegerField(default=1, help_text='Current step number in the approval workflow')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(help_text='User who submitted this request', on_delete=django.db.models.deletion.PROTECT, related_name='submitted_requests', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='core.module')),
            ],
            options={
                'db_table': 'aw_approval_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField(help_text='Step sequence number')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('WAITING', 'Waiting for Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('comments', models.TextField(blank=True, default='', help_text='Approver comments')),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='User assigned to approve this step', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_steps', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.approvalrequest')),
                ('role_required', models.ForeignKey(help_text='Role required for this step', on_delete=django.db.models.deletion.PROTECT, related_name='approval_steps', to='core.role')),
            ],
            options={
                'db_table': 'aw_approval_step',
                'ordering': ['request', 'step_order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Workflow name (e.g., 'Purchase Order Approval')", max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('total_steps', models.PositiveIntegerField(default=1, help_text='Total number of approval steps')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(help_text='Module this workflow belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='core.module')),
            ],
            options={
                'db_table': 'aw_workflow_definition',
                'ordering': ['module', 'name'],
            },
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='core.workflowdefinition'),
        ),
        migrations.CreateModel(
            name='WorkflowStepDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField(help_text='Step sequence number (1-based)')),
                ('name', models.CharField(help_text="Step name (e.g., 'Manager Review')", max_length=200)),
                ('is_optional', models.BooleanField(default=False, help_text='If true, step can be skipped')),
                ('role_required', models.ForeignKey(help_text='Role required to approve this step', on_delete=django.db.models.deletion.PROTECT, related_name='step_definitions', to='core.role')),
                ('workflow', models.ForeignKey(help_text='Parent workflow definition', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.workflowdefinition')),
            ],
            options={
                'db_table': 'aw_workflow_step_definition',
                'ordering': ['workflow', 'step_order'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISED', 'Revised'), ('REASSIGNED', 'Reassigned'), ('CANCELLED', 'Cancelled'), ('COMMENT', 'Comment Added')], max_length=50)),
                ('details', models.TextField(blank=True, default='', help_text='Human-readable action details')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('payload_snapshot', models.JSONField(default=dict, help_text='Snapshot of the request payload at this point in time')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.approvalrequest')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.approvalstep')),
            ],
            options={
                'db_table': 'aw_audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['request', 'timestamp'], name='idx_audit_req_time'), models.Index(fields=['actor', 'timestamp'], name='idx_audit_actor_time')],
            },
        ),
        migrations.AddIndex(
            model_name='approvalstep',
            index=models.Index(fields=['assigned_to', 'status'], name='idx_step_assignee_status'),
        ),
        migrations.AddIndex(
            model_name='approvalstep',
            index=models.Index(fields=['request', 'step_order'], name='idx_step_req_order'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalstep',
            unique_together={('request', 'step_order')},
        ),
        migrations.AddIndex(
            model_name='workflowdefinition',
            index=models.Index(fields=['module', 'is_active'], name='idx_wfdef_module_active'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['status', 'current_step'], name='idx_req_status_step'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['module', 'status'], name='idx_req_module_status'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['requester', 'status'], name='idx_req_requester_status'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['reference_id', 'module'], name='idx_req_ref_module'),
        ),
        migrations.AddIndex(
            model_name='workflowstepdefinition',
            index=models.Index(fields=['workflow', 'step_order'], name='idx_stepdef_wf_order'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowstepdefinition',
            unique_together={('workflow', 'step_order')},
        ),
    ]
