# Generated by Django 6.0.3 on 2026-03-30 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='callback_url',
            field=models.URLField(blank=True, help_text='URL to notify when approval status changes', max_length=500, null=True),
        ),
    ]
