# Generated by Django 6.0.3 on 2026-03-31 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='status_mapping',
            field=models.JSONField(blank=True, default=dict, help_text="Optional mapping from internal status to external status (e.g., {'APPROVED': '6'})"),
        ),
    ]
