# Generated by Django 4.2.29 on 2026-04-14 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_module_status_mapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Division or Brand name', max_length=100, unique=True)),
                ('code', models.CharField(help_text="Unique code (e.g., 'BRAND_A', 'DIV_IT')", max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Divisions',
                'db_table': 'aw_division',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='division',
            field=models.ForeignKey(blank=True, help_text='Target division/brand for this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to='core.division'),
        ),
        migrations.AddField(
            model_name='user',
            name='division',
            field=models.ForeignKey(blank=True, help_text='Assigned division/brand for contextual routing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.division'),
        ),
    ]
