# Generated by Django 6.0.3 on 2026-03-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_module_callback_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='db_host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='db_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='db_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='db_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='db_type',
            field=models.CharField(default='mysql', help_text='mysql, postgres, etc.', max_length=20),
        ),
        migrations.AddField(
            model_name='module',
            name='db_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='notification_strategy',
            field=models.CharField(choices=[('WEBHOOK', 'HTTP Webhook'), ('DATABASE', 'Direct Database Update'), ('NONE', 'None')], default='WEBHOOK', max_length=20),
        ),
        migrations.AlterField(
            model_name='module',
            name='callback_url',
            field=models.URLField(blank=True, help_text='URL for WEBHOOK strategy', max_length=500, null=True),
        ),
    ]
