# Generated by Django 6.0.3 on 2026-03-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_module_db_host_module_db_name_module_db_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='db_flag_column',
            field=models.CharField(blank=True, help_text='Column name for status/flag', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='db_reference_column',
            field=models.CharField(blank=True, help_text='Column name for reference ID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='db_table_name',
            field=models.CharField(blank=True, help_text='Table name in external DB', max_length=255, null=True),
        ),
    ]
