# Generated by Django 4.2.29 on 2026-04-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_division_approvalrequest_division_user_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='division',
            field=models.CharField(blank=True, help_text='Target division/brand code for this request', max_length=50, null=True),
        ),
    ]
