# Generated by Django 4.2.29 on 2026-04-23 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalstep',
            name='approver_type',
            field=models.CharField(choices=[('ROLE', 'Role-based'), ('USER', 'Specific User')], default='ROLE', help_text='Whether this step was assigned by role or specific user', max_length=10),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='user_required',
            field=models.ForeignKey(blank=True, help_text='Specific user required for this step', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_user_steps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowstepdefinition',
            name='approver_type',
            field=models.CharField(choices=[('ROLE', 'Role-based'), ('USER', 'Specific User')], default='ROLE', help_text='Whether to assign by role or a specific user', max_length=10),
        ),
        migrations.AddField(
            model_name='workflowstepdefinition',
            name='user_required',
            field=models.ForeignKey(blank=True, help_text='Specific user required to approve this step (if type is USER)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='step_definitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='role_required',
            field=models.ForeignKey(blank=True, help_text='Role required for this step', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_steps', to='core.role'),
        ),
        migrations.AlterField(
            model_name='workflowstepdefinition',
            name='role_required',
            field=models.ForeignKey(blank=True, help_text='Role required to approve this step (if type is ROLE)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='step_definitions', to='core.role'),
        ),
    ]
