# Generated by Django 4.2.30 on 2026-04-29 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_approvalstep_approver_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The feedback content')),
                ('type', models.CharField(choices=[('GENERAL', 'General Feedback'), ('QUESTION', 'Clarifying Question'), ('TECHNICAL_ADVICE', 'Technical Advice')], default='GENERAL', max_length=20)),
                ('is_resolved', models.BooleanField(default=False, help_text='Marked as resolved (e.g., if it was a question that has been answered)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(help_text='The approval request this feedback belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='core.approvalrequest')),
                ('user', models.ForeignKey(help_text='The user who provided this feedback', on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aw_request_feedback',
                'ordering': ['created_at'],
            },
        ),
    ]
