# Generated by Django 4.2.30 on 2026-04-29 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_requestfeedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestfeedback',
            name='is_resolved',
        ),
        migrations.RemoveField(
            model_name='requestfeedback',
            name='type',
        ),
    ]
