# Generated by Django 4.2.30 on 2026-04-29 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_requestfeedback_is_resolved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfeedback',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user who created this feedback', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
