# Generated by Django 4.2.30 on 2026-04-29 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_requestfeedback_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestfeedback',
            name='created_by',
            field=models.ForeignKey(default=1, help_text='The user who created this feedback', on_delete=django.db.models.deletion.PROTECT, related_name='feedbacks_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestfeedback',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user mentioned/targeted in this feedback', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks_targeted', to=settings.AUTH_USER_MODEL),
        ),
    ]
