# Generated by Django 4.2.30 on 2026-05-07 02:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_requestfeedback_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandWorkflowMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Example: 'Standard Approval Brand Elektronik'", max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Brand Workflow Masters',
                'db_table': 'aw_brand_workflow_master',
            },
        ),
        migrations.AddField(
            model_name='workflowstepdefinition',
            name='is_brand_conditional',
            field=models.BooleanField(default=False, help_text='If true, uses Brand-Specific Approval logic'),
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Example: 'Apple', 'Samsung'", max_length=100, unique=True)),
                ('code', models.CharField(help_text='Unique code for identification', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='core.brandworkflowmaster')),
            ],
            options={
                'db_table': 'aw_brand',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='workflowstepdefinition',
            name='brand_workflow_master',
            field=models.ForeignKey(blank=True, help_text='Link to Master Workflow Brand if is_brand_conditional is checked', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_step_definitions', to='core.brandworkflowmaster'),
        ),
        migrations.CreateModel(
            name='UserBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_users', to='core.brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_brands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aw_user_brand',
                'unique_together': {('user', 'brand')},
            },
        ),
        migrations.CreateModel(
            name='BrandWorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField()),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.brandworkflowmaster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brand_workflow_steps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aw_brand_workflow_step',
                'ordering': ['step_order'],
                'unique_together': {('master', 'step_order')},
            },
        ),
    ]
