# Generated by Django 4.2.30 on 2026-05-07 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_brandworkflowmaster_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brandworkflowstep',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='brandworkflowstep',
            name='master',
        ),
        migrations.RemoveField(
            model_name='brandworkflowstep',
            name='user',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='brand_workflow',
        ),
        migrations.RemoveField(
            model_name='workflowstepdefinition',
            name='brand_workflow_master',
        ),
        migrations.AddField(
            model_name='brand',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The user who handles approval for this brand', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_brands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='BrandWorkflowMaster',
        ),
        migrations.DeleteModel(
            name='BrandWorkflowStep',
        ),
    ]
