# Generated by Django 4.2.30 on 2026-05-08 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_brandworkflowstep_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterWorkflowCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Master Zone, Master Brand', max_length=150, unique=True)),
                ('description', models.CharField(max_length=255, unique=True)),
                ('key_param_json', models.CharField(help_text='brand_code, zone_code', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'aw_master_workflow_condition',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='master_workflow_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_workflow_conditions', to='core.masterworkflowcriteria'),
        ),
    ]
