# Generated by Django 4.2.30 on 2026-05-08 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_masterworflowcriteria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='master_workflow_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master_workflow_conditions', to='core.masterworkflowcriteria'),
        ),
    ]
