# Generated by Django 4.2.30 on 2026-05-08 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_brand_master_workflow_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstepdefinition',
            name='master_workflow_criteria',
            field=models.ForeignKey(blank=True, help_text='Criteria to find the brand/owner for conditional approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_steps', to='core.masterworkflowcriteria'),
        ),
    ]
