# Generated by Django 4.2.30 on 2026-05-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_workflowstepdefinition_master_workflow_criteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterworkflowcriteria',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
