# Generated by Django 4.2.30 on 2026-05-12 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_requestwatcher_deleted_at_requestwatcher_deleted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstepdefinition',
            name='conditions',
            field=models.JSONField(blank=True, default=list, help_text="List of conditions to require/skip this step. Example: [{'field': 'total_amount', 'operator': '>', 'value': 1000000}]"),
        ),
        migrations.CreateModel(
            name='ModuleVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name (e.g., 'Total Amount')", max_length=100)),
                ('key_name', models.CharField(help_text="Key in JSON payload (e.g., 'total_amount')", max_length=100)),
                ('data_type', models.CharField(choices=[('NUMBER', 'Number'), ('STRING', 'String'), ('BOOLEAN', 'Boolean')], default='STRING', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='core.module')),
            ],
            options={
                'db_table': 'aw_module_variable',
                'ordering': ['module', 'name'],
                'unique_together': {('module', 'key_name')},
            },
        ),
    ]
