# Generated by Django 4.2.30 on 2026-06-15 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_workflowstepdefinition_conditions_modulevariable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('WAITING', 'Waiting for Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped'), ('ADDITIONAL', 'Additional Action Required')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISED', 'Revised'), ('REASSIGNED', 'Reassigned'), ('CANCELLED', 'Cancelled'), ('FEEDBACK', 'Feedback Added'), ('WATCHER_ADDED', 'Watcher Added'), ('WATCHER_REMOVED', 'Watcher Removed')], max_length=50),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_users', to='core.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aw_user_role',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
