# Generated by Django 4.2.30 on 2026-06-17 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_user_role_alter_approvalstep_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='dept',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(db_column='title', on_delete=django.db.models.deletion.CASCADE, related_name='role_users', to='core.role', to_field='code'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
        migrations.AlterModelTable(
            name='userrole',
            table='user_title_matrix',
        ),
    ]
