# Generated by Django 4.2.30 on 2026-06-23 02:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_userrole_dept_alter_user_email_alter_userrole_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(help_text='API Endpoint called', max_length=500)),
                ('method', models.CharField(help_text='HTTP Method (GET, POST, etc.)', max_length=20)),
                ('payload', models.JSONField(blank=True, help_text='Request payload (passwords scrubbed)', null=True)),
                ('response_status', models.IntegerField(help_text='HTTP Response Status Code')),
                ('error_message', models.TextField(blank=True, help_text='Error message if the request failed', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('execution_time_ms', models.FloatField(help_text='Execution time in milliseconds')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who made the request (if authenticated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aw_api_audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['response_status', 'timestamp'], name='idx_api_audit_status_time'), models.Index(fields=['endpoint', 'timestamp'], name='idx_api_audit_endpoint_time')],
            },
        ),
    ]
