# Generated by Django 4.2.30 on 2026-09-16 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_apiauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCEmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address to receive CC notifications', max_length=254)),
                ('subject', models.CharField(default='eorder information', help_text="Target email subject option (e.g. 'eorder information')", max_length=150)),
                ('is_active', models.BooleanField(default=True, help_text='Active status flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this config', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cc_email_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aw_cc_email_config',
                'ordering': ['-created_at'],
                'unique_together': {('email', 'subject')},
            },
        ),
    ]
