# Generated by Django 4.2.30 on 2026-09-29 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_ccemailconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalstep',
            name='required_inputs',
            field=models.JSONField(blank=True, default=list, help_text="Required input keys approver must fill (e.g. ['po_number', 'quotation'])"),
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='step_data',
            field=models.JSONField(blank=True, default=dict, help_text='Data entered by approver during step execution (e.g., PO Number & Quotation)'),
        ),
        migrations.AddField(
            model_name='workflowstepdefinition',
            name='required_inputs',
            field=models.JSONField(blank=True, default=list, help_text="List of required input field keys approver must fill (e.g. ['po_number', 'quotation'])"),
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='approver_type',
            field=models.CharField(choices=[('ROLE', 'Role-based'), ('USER', 'Specific User'), ('REQ_DEPT_HEAD', 'Requestor Dept Head'), ('FINANCE_DEPT_HEAD', 'Finance Dept Head / Team'), ('TARGET_DEPT_ROLE', 'Target Dept Role')], default='ROLE', help_text='Whether this step was assigned by role, user, dept head, or finance', max_length=30),
        ),
        migrations.AlterField(
            model_name='workflowstepdefinition',
            name='approver_type',
            field=models.CharField(choices=[('ROLE', 'Role-based'), ('USER', 'Specific User'), ('REQ_DEPT_HEAD', 'Requestor Dept Head'), ('FINANCE_DEPT_HEAD', 'Finance Dept Head / Team'), ('TARGET_DEPT_ROLE', 'Target Dept Role')], default='ROLE', help_text='Approver designation type', max_length=30),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Department name (e.g., 'Finance', 'Marketing', 'Procurement')", max_length=100, unique=True)),
                ('code', models.CharField(help_text="Unique code (e.g., 'DEPT_FIN', 'DEPT_MKT')", max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dept_head', models.ForeignKey(blank=True, help_text='User designated as the Head of this Department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aw_department',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='target_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_approval_steps', to='core.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='department_ref',
            field=models.ForeignKey(blank=True, help_text='Linked Department instance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_users', to='core.department'),
        ),
        migrations.AddField(
            model_name='workflowstepdefinition',
            name='target_department',
            field=models.ForeignKey(blank=True, help_text='Target department for TARGET_DEPT_ROLE step', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step_definitions', to='core.department'),
        ),
    ]
