# Generated by Django 4.2.30 on 2026-09-29 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_department_and_step_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Company name (e.g., 'PT. Sinar Jaya', 'PT. Global Distribusi')", max_length=150, unique=True)),
                ('code', models.CharField(help_text="Unique company code (e.g., 'PT_SJ', 'PT_GD')", max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'aw_company',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='company_code',
            field=models.CharField(blank=True, default='', help_text='Company code string', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='company_ref',
            field=models.ForeignKey(blank=True, help_text='Linked Company instance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_users', to='core.company'),
        ),
        migrations.CreateModel(
            name='OrganizationStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(help_text='e.g. Staff Marketing, Manager Marketing, Head of Department', max_length=150)),
                ('level_order', models.PositiveIntegerField(default=1, help_text='Hierarchy level: 1=Staff, 2=Manager, 3=Dept Head, 4=Director')),
                ('is_dept_head', models.BooleanField(default=False, help_text='True if this node is the Department Head')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Company this node belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='org_structures', to='core.company')),
                ('department', models.ForeignKey(help_text='Department within the company', on_delete=django.db.models.deletion.CASCADE, related_name='org_structures', to='core.department')),
                ('reports_to', models.ForeignKey(blank=True, help_text='Direct manager or department head to report to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Employee user', on_delete=django.db.models.deletion.CASCADE, related_name='org_positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aw_organization_structure',
                'ordering': ['company', 'department', 'level_order'],
                'unique_together': {('company', 'user', 'department')},
            },
        ),
    ]
