# Generated by Django 4.2.30 on 2026-09-29 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_company_and_org_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.ForeignKey(default=1, help_text='Linked Company instance', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.company'),
            preserve_default=False,
        ),
    ]
