# Generated by Django 4.2.30 on 2026-09-30 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_department_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='company_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_ref',
        ),
    ]
