# Generated by Django 4.2.30 on 2026-09-30 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_user_company_code_remove_user_company_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='department_ref',
        ),
    ]
