# Generated by Django 4.2.30 on 2026-09-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_user_department_remove_user_department_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalstep',
            name='approver_type',
            field=models.CharField(choices=[('ROLE', 'Role-based'), ('USER', 'Specific User'), ('REQ_DEPT_HEAD', 'Requestor Dept Head'), ('FINANCE_DEPT_HEAD', 'Finance Dept Head / Team'), ('PURCH_DEPT_HEAD', 'Purchasing Approval'), ('TARGET_DEPT_ROLE', 'Target Dept Role')], default='ROLE', help_text='Whether this step was assigned by role, user, dept head, or finance', max_length=30),
        ),
        migrations.AlterField(
            model_name='workflowstepdefinition',
            name='approver_type',
            field=models.CharField(choices=[('ROLE', 'Role-based'), ('USER', 'Specific User'), ('REQ_DEPT_HEAD', 'Requestor Dept Head'), ('FINANCE_DEPT_HEAD', 'Finance Dept Head / Team'), ('PURCH_DEPT_HEAD', 'Purchasing Approval'), ('TARGET_DEPT_ROLE', 'Target Dept Role')], default='ROLE', help_text='Approver designation type', max_length=30),
        ),
    ]
