# Generated by Django 4.2.30 on 2026-10-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_approvalstep_approver_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ccemailconfig',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ccemailconfig',
            name='ship_to',
            field=models.CharField(blank=True, help_text='Target Ship To code for filtering CC recipients', max_length=50, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='ccemailconfig',
            unique_together={('email', 'subject', 'ship_to')},
        ),
    ]
