# Generated by Django 4.2.30 on 2026-10-07 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_ccemailconfig_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Asset Code / Tag Number', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Asset Name / Description', max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'aw_master_asset',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MasterEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Equipment Code', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Equipment Name', max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'aw_master_equipment',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MasterGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Goods Code', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Goods Name', max_length=255)),
                ('unit', models.CharField(default='PCS', max_length=50)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'aw_master_goods',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MasterWBS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='WBS Element Code', max_length=50, unique=True)),
                ('description', models.CharField(help_text='WBS Description', max_length=255)),
                ('project_name', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'aw_master_wbs',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PRNonTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, db_index=True, help_text='Format: PR/{code_name}/NT/{year}/{6_digit_running_number}', max_length=100, null=True, unique=True)),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('requestor_name', models.CharField(max_length=255)),
                ('requester_department', models.CharField(blank=True, default='', max_length=255)),
                ('requester_company', models.CharField(blank=True, default='', max_length=255)),
                ('purpose', models.TextField(blank=True, default='')),
                ('goods_service_type', models.CharField(choices=[('lumpsum', 'Lumpsum'), ('not_lumpsum', 'Not Lumpsum')], default='not_lumpsum', max_length=20)),
                ('purchase_type', models.CharField(choices=[('asset', 'Asset'), ('non_asset', 'Non Asset')], default='non_asset', max_length=20)),
                ('car_tbr_no', models.CharField(blank=True, default='', max_length=100)),
                ('asset_type', models.CharField(choices=[('non_wbs', 'Non WBS'), ('wbs', 'WBS')], default='non_wbs', max_length=20)),
                ('asset_no', models.CharField(blank=True, default='', max_length=100)),
                ('wbs_no', models.CharField(blank=True, default='', max_length=100)),
                ('equipment_name', models.CharField(blank=True, default='', max_length=255)),
                ('submission_remark', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pr_non_trade_headers', to='core.approvalrequest')),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pr_non_trade_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'aw_pr_non_trade',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PRNonTradeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'aw_pr_non_trade_sequence',
                'unique_together': {('code_name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PRNonTradeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_order', models.PositiveIntegerField(default=1)),
                ('goods_code', models.CharField(max_length=100)),
                ('goods_name', models.CharField(max_length=255)),
                ('unit', models.CharField(default='PCS', max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=12)),
                ('remark', models.TextField(blank=True, default='')),
                ('pr_non_trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.prnontrade')),
            ],
            options={
                'db_table': 'aw_pr_non_trade_item',
                'ordering': ['item_order', 'id'],
            },
        ),
    ]
