# Generated by Django 4.2.30 on 2026-10-08 01:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_masterasset_masterequipment_mastergoods_masterwbs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prnontrade',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
